on:
 push:
   branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - run: docker build python

  login:
    runs-on: [ubuntu-latest]
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  push:
    runs-on: [ubuntu-latest]
    steps:
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: python:latest
